### ISSUE TITLE
Rending issue on production

### ISSUE THREAD

**Issue by 3lonious** [rive-app/rive-react#105]
everything works localy but when i go live there is nothing rendering.

**Comment by zplata** [comment]
@3lonious Hi 👋 , caught your notes from your comments on other issues, sorry to hear you're getting blocked here! 

You may have caught it from the other thread https://github.com/rive-app/rive-react/issues/97#issuecomment-1168748311

But this library does need to make a request out to retrieve a WASM file that really drives the rendering for the JS/React libs. I think it makes sense to look at a solution to make it so you can retrieve the file/store the file on your own and supply it to the high-level API, but until then, I'd be curious to learn more about why it's not rendering when you build/deploy. Do you have any network request issues when it tries to retrieve the WASM in logs of any kind (i.e is it getting blocked by your web server?)

**Comment by 3lonious** [comment]
ok so here are screen shots.. both localy, you can see it render.. and then production where it wont render, but network requests look like they are comming thru 200...

Also ive set this up with useRive, and useStateMachine or whatever and exact same issue...

is there anything on the backend that needs setting up? im deploying thru github actions and amplify aws, would love to get these animiations working..

**Comment by 3lonious** [comment]
<img width="1766" alt="Screen Shot 2022-07-01 at 4 35 00 PM" src="https://user-images.githubusercontent.com/46793692/176978077-8e0070c9-c0db-4438-a292-691a145fcabd.png">

**Comment by 3lonious** [comment]
<img width="2357" alt="Screen Shot 2022-07-01 at 4 36 41 PM" src="https://user-images.githubusercontent.com/46793692/176978090-65107071-4740-4bdc-bcf5-8033dfdc3beb.png">

**Comment by 3lonious** [comment]
Production


<img width="2221" alt="Screen Shot 2022-07-01 at 4 40 44 PM" src="https://user-images.githubusercontent.com/46793692/176978129-6a00f185-ec08-4b6c-9c82-a8924b8b7e7a.png">

**Comment by zplata** [comment]
@3lonious Rive doesn't require any server-side or "backend" work, as it's a library meant to work with your client-side. So a few follow-ups:

Do you mind sharing any snippets of code on how you're setting it up? Are you hosting your `.riv` file?
Any console errors?

**Comment by 3lonious** [comment]
import Turbo from "../../../assets/rive/65-358-iron-giant-demo.riv";


import Rive, { useRive, useStateMachineInput } from "rive-react";

 const { rive, RiveComponent } = useRive({
    src: Mixer,
    autoplay: true,
  })
     <Rive src={Mixer} autoplay="true" className="mx-auto w-32 h-32  shadow-md "/>

**Comment by 3lonious** [comment]
import Turbo from "../../../assets/rive/65-358-iron-giant-demo.riv";


import Rive, { useRive, useStateMachineInput } from "rive-react";

 const { rive, RiveComponent } = useRive({
    src: Mixer,
    autoplay: true,
  })
  
<Rive src={Mixer} autoplay="true" className="mx-auto w-32 h-32  shadow-md "/>

**Comment by 3lonious** [comment]
ok i found errors in console

**Comment by 3lonious** [comment]
<img width="1766" alt="Screen Shot 2022-07-01 at 7 27 15 PM" src="https://user-images.githubusercontent.com/46793692/176983423-a8fcd02d-181a-4009-a522-5e871efea69d.png">
<img width="706" alt="Screen Shot 2022-07-01 at 7 27 32 PM" src="https://user-images.githubusercontent.com/46793692/176983426-726bda55-2245-4cfb-b634-181c7e4773a3.png">
<img width="1419" alt="Scree
<img width="1813" alt="Screen Shot 2022-07-01 at 7 28 02 PM" src="https://user-images.githubusercontent.com/46793692/176983435-7138eed1-05c3-499f-bcea-91b624cc616a.png">
n Shot 2022-07-01 at 7 27 43 PM" src="https://user-images.github
<img width="1857" alt="Screen Shot 2022-07-01 at 7 27 53 PM" src="https://user-images.githubusercontent.com/46793692/176983432-8ac402bc-73d9-4a86-ac42-78275e519323.png">
usercontent.com/46793692/176983428-3201162e-4e5e-4622-901a-7b03d42aa06b.png">

**Comment by 3lonious** [comment]
<img width="1419" alt="Screen Shot 2022-07-01 at 7 27 43 PM" src="https://user-images.githubusercontent.com/46793692/176983464-4098dc28-0c8f-4e6b-aeaf-8e120d77dafb.png">

**Comment by 3lonious** [comment]
<img width="706" alt="Screen Shot 2022-07-01 at 7 27 32 PM" src="https://user-images.githubusercontent.com/46793692/176983472-1847d448-b5fd-444a-8b7c-6a5834b980cc.png">

**Comment by 3lonious** [comment]
<img width="1885" alt="Screen Shot 2022-07-01 at 7 27 07 PM" src="https://user-images.githubusercontent.com/46793692/176984401-478a0e50-5b76-4d05-b493-6132d1a63700.png">

**Comment by 3lonious** [comment]
also links to our audio mastering platform if it helps

https://chosenmasters.com/

https://pro.chosenmasters.com/register

**Comment by 3lonious** [comment]
Any luck here? is there something that needs extra config?

**Comment by 3lonious** [comment]
just realized you put this on the other thread... im gonna give this a try thanks :)
<img width="1100" alt="Screen Shot 2022-07-05 at 10 03 36 AM" src="https://user-images.githubusercontent.com/46793692/177379851-4d4ba89b-9548-486f-81de-37c71cbc7ac9.png">

**Comment by 3lonious** [comment]
my solution
                  import Rive from "rive-react";

                <Rive  autoplay="true" src="https://public.rive.app/community/runtime-files/65-358-iron-giant-demo.riv" />
                
                you can get the url for src="" by looking thru community animations, inspect element, go to network tab and copy .riv url from network request
                
<img width="1701" alt="Screen Shot 2022-07-05 at 1 34 32 PM" src="https://user-images.githubusercontent.com/46793692/177411737-ab5eeb80-e2d1-4b6d-b127-a6ce0e241a3e.png">
<img width="677" alt="Screen Shot 2022-07-05 at 1 34 38 PM" src="https://user-images.githubusercontent.com/46793692/177411776-f29b0386-a3f5-46ce-8d4a-cacd1697b548.png">

**Comment by zplata** [comment]
Closing this since the issue seems to have been resolved
