### ISSUE TITLE
Rive.wasm 404 Not Found

### ISSUE THREAD

**Issue by smarais97** [rive-app/rive-react#118]
Hi everyone, first time trying Rive in React.

I ran the npm install command for react-canvas as specified. I added my .riv file (The hamburger menu example one) and after importing as per the docs and running npm start, I get a blank screen. When looking at the logs I get the following error:
_Failed to load resource: the server responded with a status of 404. https://unpkg.com/@rive-app/canvas@1.0.0/rive.wasm_

![image](https://user-images.githubusercontent.com/12349670/187537045-7ab4db8c-3a77-4b23-8e49-80d4ae3e7a77.png)

When accessing that URL:
![image](https://user-images.githubusercontent.com/12349670/187537184-c04e0cab-4913-402e-ab6c-4000f7e824f8.png)

I can see that this URL is generated in Rive.js with RuntimeLoader.wasmURL. Is the correct URL:
https://unpkg.com/rive-canvas@latest/rive.wasm

And if so what can I do to make sure that it selects an existing rive.wasm file and not one that doesn't exist.

The code:
![image](https://user-images.githubusercontent.com/12349670/187537647-3eb0060b-3157-4409-a1a5-98fd022f557f.png)

Package installed:
npm i --save @rive-app/react-canvas

**Comment by yagiz-aydin** [comment]
Downgraded to  "@rive-app/canvas": "^1.0.82" it works now.

**Comment by zplata** [comment]
Really odd! We were doing some dependency upgrades here with some recent changes to the underlying WASM file in the JS runtime (`@rive-app/canvas`). Can you try with `3.0.23` that released today? 

Thanks for raising this, @smarais97 .

**Comment by smarais97** [comment]
Thanks for the replies guys! After the latest update, it is working correctly.

All the best.
