### ISSUE TITLE
Offline functionality.

### ISSUE THREAD

**Issue by felix-wolf** [rive-app/rive-react#139]
I am creating an Electron Application using React as a frontend framework that is likely to be used in an offline scenario.

I would like to play a Rive animation, but the library tries to access https://unpkg.com/@rive-app/canvas@1.0.95/rive.wasm. Is there a way to play the animation without accessing anything from the web first?

**Comment by zplata** [comment]
You should be able to load in the WASM yourself by hosting it where needed:
https://help.rive.app/runtimes/overview/web-js/preloading-wasm

**Comment by felix-wolf** [comment]
I will check this out, thank you.
