### ISSUE TITLE
Rive component not rendering in NextJS

### ISSUE THREAD

**Issue by felipesses** [rive-app/rive-react#162]
Hi, I am using NextJs in my project and my Rive component is not rendering, 

I have imported the `@rive-app/react-canvas` package and I'm using the current version, "^3.0.38"

Here's my folder
![Captura de Tela 2023-03-15 às 11 00 08](https://user-images.githubusercontent.com/45373166/225331794-ecd78789-8054-4aa4-aac6-fb4eda3cbeeb.png)

The component
![Captura de Tela 2023-03-15 às 11 00 33](https://user-images.githubusercontent.com/45373166/225331920-b5af718a-2a69-4549-a8ab-67a0e509ecaa.png)

It seems like the canvas is rendering, but it doesn't show anything
![Captura de Tela 2023-03-15 às 11 00 48](https://user-images.githubusercontent.com/45373166/225332008-274de1c2-448c-41cb-98d2-e7e7847d5642.png)

**Comment by felipesses** [comment]
> Hey @felipesses
> 
> Your canvas height is being set to 0. Do you know what could be causing that?
> 
> Could you share some code so I could reproduce this locally? A link to a github repo I could clone would be ideal.

Hey! I have found the issue. I had to set the height of the component otherwise it renders so small that I couldn't see it 😅 thanks for the reply!

**Comment by Klynger** [comment]
I'm having the same issue. It feels limiting having to set a fixed height to make it work, and it doesn't work if the user resizes the window.
