### ISSUE TITLE
AWS amplify -  Problem loading file; may be corrupt!

### ISSUE THREAD

**Issue by happy-cutman** [rive-app/rive-react#176]
**Conditions:**

- create-react-app
- .riv file in public folder ```public/connectButton.riv```
- local build works fine without errors

The error occurs on a deployed application. sees the file, but does not seem to recognize it

![image](https://user-images.githubusercontent.com/43891296/233643473-35c908c6-4e67-4717-b3eb-309e604a3db7.png)

The same file on local build

![image](https://user-images.githubusercontent.com/43891296/233643588-573d2779-d925-44b4-baaf-221e1043c638.png)

```
const WalletAnimation = () => {
  const { rive, RiveComponent } = useRive({
    src: 'connectButton.riv',
    autoplay: true
  });

 return (
    <Wrapper>
      <RiveComponent/>
    </Wrapper>
  );
};

export default WalletAnimation;
```

**Comment by caudetgit** [comment]
@happy-cutman You may need to specify the mimetype in Amplify for .riv (application/octet-stream)

**Comment by happy-cutman** [comment]
Thanks man! Maybe there are more detailed instructions on how to do it? I know it's not a stackoverflow, but I really need
