### ISSUE TITLE
Using Rive-react in nestjs

### ISSUE THREAD

**Issue by es404020** [rive-app/rive-react#27]
./node_modules/rive-js/dist/rive.dev.js:101:0
Module not found: Can't resolve 'fs'

**Comment by avivian** [comment]
hey @es404020, could you provide some more context into how you are using rive-react with nestjs? I haven't used nestjs myself, but it seems to be a server side framework.

**Comment by avivian** [comment]
Going to close, haven't had any response

**Comment by es404020** [comment]
yes i have thanks
