### ISSUE TITLE
Questions about Rive Text UTF-8 support

### ISSUE THREAD

**Issue by kj4483** [rive-app/rive-react#294]
I’ve noticed an issue in the Rive Text demo code where characters in Korean, Chinese, Japanese, and emojis are not displayed correctly. It seems that UTF-8 encoding might not be applied. Is this issue specific to the demo code, or does Rive Text not support these languages by default?

I haven’t tested this in a separate project yet, and I couldn’t find relevant information through my search, so I’m asking for clarification here.

[Rive Text demo code](https://codesandbox.io/p/sandbox/rive-text-js-forked-5pw3yy?file=%2Fsrc%2Findex.mjs%3A21%2C5)

**Comment by kj4483** [comment]
Thank you for kind explanation!!

**Comment by kj4483** [comment]
I have a related question. 

Is it supported to use emoji entered at runtime? When I type in an emoji in Rive Editor, it doesn't look right.


<img width="198" alt="image" src="https://github.com/user-attachments/assets/133afb4a-5770-41c3-95a5-1c7ec86f3b55">

**Comment by HayesGordon** [comment]
@kj4483 we don't support emojis at this time. It may be possible in the future through a different mechanism, and we've chatted internally about a few options
