### ISSUE TITLE
No support for static rives

### ISSUE THREAD

**Issue by kadenBeckstead** [rive-app/rive-react#41]
I've implemented the rive-react package and am loading rives with the `useRive` hook. When downloaded and tested my configuration with the `poison-loader.riv` file from this repo it worked great. When I tried to use one of my own (that has no animations) it throws an error saying `Artboard has no animations`. 

I'd like to be able to load and use all my assets (animated and otherwise) into the app just using the rive package. Is this possible or will this be possible in the future?

Seems like this repo should be able to support rive files which are static and have no animations. Thanks! 

![image](https://user-images.githubusercontent.com/46738126/135008703-9c335af8-d21e-4b2d-88c9-5da3940a60c0.png)

**Comment by avivian** [comment]
Hey @kadenBeckstead, we currently don't supporting playing rive files without animations. The simple workaround for this is to add an animation to the artboard with no keyframes and export your file again.
