### ISSUE TITLE
Animation becomes slow after a while (memory leak?)

### ISSUE THREAD

**Issue by a-y-u-s-h** [rive-app/rive-react#55]
Have a look at this video:

https://user-images.githubusercontent.com/19586719/149635636-594687cc-bb11-4a90-baaf-219a2ee0238a.mp4

I'm using [this](https://rive.app/community/520-990-teddy-login-screen/) animation in my application. After the app is left to run for a while, it starts lagging (as shown in the initial part of the video), after a refresh it works fine for a while. Maybe there's a memory leak somewhere.

**Comment by avivian** [comment]
Hey @a-y-u-s-h, thanks for raising this! I've investigated and found a bug in our render loop, which has now been fixed. If you upgrade to version `0.0.31` of `rive-react` you should not see this lagging any more.

**Comment by hmmhmmhm** [comment]
> Hey @a-y-u-s-h, thanks for raising this! I've investigated and found a bug in our render loop, which has now been fixed. If you upgrade to version `0.0.31` of `rive-react` you should not see this lagging any more.

Thank you! I had the same issue, and I solved it easily by updating the version!
