### ISSUE TITLE
HTML <canvas> Accessibility

### ISSUE THREAD

**Issue by PaulieScanlon** [rive-app/rive-react#68]
Hi team. I've been experimenting with Rive and accessibility and noticed that when i add `role` or `aria-label` attributes to `RiveComponent` they appear in the DOM on the containing div rather than on the HTML `canvas` element. 

Is this by design?

```javascript
// usage

<RiveComponent className={className} role="img" aria-label="fun time animation" />;
```

```html
// output

<div class="fun-time-animation" role="img" aria-label="fun time animation">
   <canvas style="vertical-align: top; width: 500px; height: 500px;" width="1000" height="1000"></canvas>
</div>
```

I'm currently using ` "rive-react": "^1.0.4"`

**Comment by zplata** [comment]
@PaulieScanlon Can you try testing with our new dependency `@rive-app/react-canvas` v2.0.0? There should be no API changes needed on your end, but the attributes you're passing in should propagate to the canvas instead of that wrapping `div` now.

**Comment by PaulieScanlon** [comment]
Hey @zplata Yep. Confrimed. I've upgraded to ` "rive-react": "^2.0.0"` and now both the `role` and `aria-label` are passed on to the Canvas. Brills job team!! 

Demo:
https://gatsbyrivereactruntime.gatsbyjs.io/
