### ISSUE TITLE
Failed to fetch in Nextjs

### ISSUE THREAD

**Issue by ivajo26** [rive-app/rive-react#90]
I was working with version 0.0.22 but when updating to version 3.0.0 I get this error. I am using NextJs.

![image](https://user-images.githubusercontent.com/6981217/171495101-e02b4d96-3dd0-4087-b51d-378d61682a3e.png)

```
 8;for(var l=0;l<g;l++){var h=D[n+l],p=sc[b];0===h||10===h?((1===b?ua:xa)(Ca(p,0)),p.length=0):p.push(h)}e+=g}I[d>>2]=e;return 0},A:function(){}};
  121 | (function(){function b(e){k.asm=e.exports;za=k.asm.N;Ra();Sa=k.asm.T;Ua.unshift(k.asm.O);Xa--;k.monitorRunDependencies&&k.monitorRunDependencies(Xa);0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za&&(e=Za,Za=null,e()))}function a(e){b(e.instance)}function c(e){return cb().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){xa("failed to asynchronously prepare wasm: "+f);ta(f)})}var d={a:wc};Xa++;k.monitorRunDependencies&&k.monitorRunDependencies(Xa);
> 122 | if(k.instantiateWasm)try{return k.instantiateWasm(d,b)}catch(e){return xa("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ya||"function"!==typeof WebAssembly.instantiateStreaming||$a()||L.startsWith("file://")||"function"!==typeof fetch?c(a):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(a,function(f){xa("wasm streaming compile failed: "+f);xa("falling back to ArrayBuffer instantiation");return c(a)})})})().catch(ba);
      |                                                                                                                                                  ^
  123 | return{}})();k.___wasm_call_ctors=function(){return(k.___wasm_call_ctors=k.asm.O).apply(null,arguments)};var tb=k._free=function(){return(tb=k._free=k.asm.P).apply(null,arguments)},vc=k._malloc=function(){return(vc=k._malloc=k.asm.Q).apply(null,arguments)},sb=k.___getTypeName=function(){return(sb=k.___getTypeName=k.asm.R).apply(null,arguments)};k.___embind_register_native_and_builtin_types=function(){return(k.___embind_register_native_and_builtin_types=k.asm.S).apply(null,arguments)};
  124 | k.dynCall_jiji=function(){return(k.dynCall_jiji=k.asm.U).apply(null,arguments)};var xc;Za=function yc(){xc||zc();xc||(Za=yc)};
  125 | function zc(){function b(){if(!xc&&(xc=!0,k.calledRun=!0,!Aa)){db(Ua);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var a=k.postRun.shift();Va.unshift(a)}db(Va)}}if(!(0<Xa)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Wa();db(Ta);0<Xa||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);b()},1)):b())}}
```

**Comment by zplata** [comment]
@ivajo26 Thanks for reporting - do you have a sample project to reproduce?

**Comment by 3lonious** [comment]
im using Tailwind in my project... wondering if my rending probem is related toi tailwind or maybe its like what Ivajo is dealing with?


here is my file im having issues with 



import React, { useState, useRef, useEffect, useCallback } from "react";
import { connect } from "react-redux";
// import Slider from "rc-slider";
import toaster from "toasted-notes";

import { MASTERING_STORAGE_URL } from "../../../config";
import {
  pausePlayCurrentPlay,
  setRepeatAll,
  setRepeatOne,
  setShuffle,
} from "../../../redux/actions/music";
import { downloadMusic } from "../../../services/music";

import "./Player.css";

import { useRive, useStateMachineInput } from "rive-react";
import Mixer from "../../../assets/rive/65-358-iron-giant-demo.riv";

const Intensity = ({ status, volume, handleRange }) => {
  return (
    <div className="intensity__card">
      <div class="range-input">
        <input
          className="range__input"
          value={volume}
          onChange={(e) => handleRange(e, "intensity")}
          type="range"
          min="0"
          max={status === "mastered" ? "9" : "5"}
          step="1"
        />
        <div class="value ranged_value m-2">{+volume + 1}</div>
      </div>
    </div>
  );
};



const Player = ({ song, user, togglePlayer, masterSong, setLoadingSong }) => {
  const [currentTime, setCurrentTime] = useState("0:00");
  const [status, setStatus] = useState(song.mastered ? "mastered" : "demo"); //originial, mastered
  const [mode, setMode] = useState("0");
  const [volume, setVolume] = useState(3);
  const [showIntensity, setShowIntensity] = useState(false);
  const [songData, setSongData] = useState({ songUrl: "", json: "" });
  const [waveloading, setWaveLoading] = useState(true);
  const [masteringDurationLeft, setMasteringDurationLeft] = useState("");


  const handleGetData = async () => {
    let url;
    let json;

    if (status === "original") {
      //play unmastered version
      setStatus("original");
      url = `${MASTERING_STORAGE_URL}/${user.id}/${song.uid}/${song.uid}.${song.ext}`;
      json = `${MASTERING_STORAGE_URL}/${user.id}/${song.uid}/${song.uid}.${song.ext}/original_upload.json`;
    } else {
      if (!song.mastered) {
        setStatus("demo");
        url = `${MASTERING_STORAGE_URL}/${user.id}/${song.uid}/${song.uid}.${
          song.ext
        }/mode_${mode}/demo/${song.uid}_V${volume}_${setModeString(
          mode
        )}_chosenmasters.mp3`;
        json = `${MASTERING_STORAGE_URL}/${user.id}/${song.uid}/${song.uid}.${
          song.ext
        }/mode_${mode}/demo/json/${song.uid}_V${volume}_${setModeString(
          mode
        )}_chosenmasters.json`;
      } else {
        setStatus("mastered");
        url = `${MASTERING_STORAGE_URL}/${user.id}/${song.uid}/${song.uid}.${
          song.ext
        }/mode_${mode}/${song.uid}_V${volume}_${setModeString(
          mode
        )}_chosenmasters.mp3`;
        json = `${MASTERING_STORAGE_URL}/${user.id}/${song.uid}/${song.uid}.${
          song.ext
        }/mode_${mode}/json/${song.uid}_V${volume}_${setModeString(
          mode
        )}_chosenmasters.json`;
      }
    }

    try {
      console.log(`==1==`);
      let resp = await fetch(json);
      console.log(`==resp==`);
      console.log(resp);
      console.log(resp.ok);
      if (!resp.ok) {
        setTimeout(() => {
          handleGetData();
          setMasteringDurationLeft("Thanks for your patience! This may take up to a minute or 2 depending on the size of your file");
        }, 4000);
        return;
      } else {
        setTimeout(() => {
          console.log(`==setLoadingSong called==`);
          setLoadingSong(false);
        }, 5000);
      }
      console.log(`==2==`);
      let data = await resp.json();
      console.log(`==data==`);
      console.log(data);
      if (!resp.ok) {
        console.log(`==3==`);
        setTimeout(() => {
          console.log(`==setSongData called==`);
          setSongData({
            songUrl: url,
            json: data.data,
          });
        }, 4000);
      }
    } catch (error) {
      console.log(`==error==`);
      console.log(error);
      setTimeout(() => {
        handleGetData();
        setMasteringDurationLeft("This may take up to a minute");
      }, 4000);
    }
  };

  useEffect(() => {
    handleGetData();
  }, [song, status, mode, volume, user.id]);

  const setModeString = (value) => {
    if (value === "0") {
      return "Powerful";
    }
    if (value === "1") {
      return "Elevate";
    }
    if (value === "2") {
      return "Airy";
    }
  };

  const handleToggle = (e) => {
    e.stopPropagation();
    togglePlayer();
  };

  const handleStatusToggle = (e) => {
    if (e.target.checked === true) {
      setStatus(song.mastered ? "mastered" : "demo");
    } else {
      setStatus("original");
    }
  };

  const handlePlayerClick = (e) => {
    if (e.target.classList[0]) {
      if (
        e.target.classList[0].includes("intensity") ||
        e.target.classList[0].includes("range")
      ) {
      } else {
        setShowIntensity(false);
      }
    } else {
      setShowIntensity(false);
    }
  };

  const startDownload = async (song) => {
    toaster.notify("Your download will start shortly", {
      duration: 4000,
      position: "bottom",
    });

    const key = {
      key: songData.songUrl.replace(MASTERING_STORAGE_URL, ""),
      name: `${song.title}.${song.ext}`,
      type: "mastering",
    };
    const response = await downloadMusic(key);
    const url = response.url;
    let app = document.querySelector("#root");
    let a = document.createElement("a");
    a.setAttribute("href", url);
    a.setAttribute("target", "_self");
    a.setAttribute("download", song.title);
    app.append(a);
    a.click();
  };

  const { rive, RiveComponent } = useRive({
    src: Mixer,
    autoplay: true,
  })

  return (
    <div className="player__main w-screen" onClick={handlePlayerClick}>
      <div className="player__container p-4 h-32 mx-auto mt-56 transform -translate-y-40 md:-translate-y-0 md:translate-x-2 md:w-8/12">
        <p onClick={handleToggle} className="text-right">
          <i
            className="fas fa-times"
            style={{ fontSize: "35px", color: "#fff", cursor: "pointer" }}
          ></i>
        </p>
        <div className="bg-indigo-500 filter brightnes-50  svgtheme p-4 rounded-3xl ">
          <div className="row settings">
            <div className="col-md-7 d-flex align-items-center">
              {/* <div className="d-flex mt-5">
                <span>Original</span>
                <label class="switch">
                  <input
                    checked={status === "original" ? false : true}
                    onChange={(e) => handleStatusToggle(e)}
                    type="checkbox"
                  />
                  <div></div>
                </label>
                <span>{song.mastered ? "Mastered" : "Demo"}</span>
              </div>
              <div className="mr-3">
                {status !== "original" && (
                  <>
                    <label>Mastering Style</label>
                    <select
                      value={mode}
                      onChange={(e) => setMode(e.target.value)}
                    > 
                      <option value="0">Powerful</option>
                      <option value="1">Elevate</option>
                      <option value="2">Airy</option>
                    </select>
                  </>
                )}
              </div> */}
              {/* <div>
                {status === "mastered" || status === "demo" ? (
                  <>
                    {showIntensity && (
                      <Intensity
                        status={status}
                        volume={volume}
                        handleRange={() => {}}
                      />
                    )}
                    <label>Select Intensity</label>
                    <div
                      className="intensity__box"
                      onClick={() => setShowIntensity(!showIntensity)}
                    >
                      <i
                        className="fas fa-volume-up"
                        style={{ color: "#fff" }}
                      ></i>
                      <span className="intensity__span">Intensity</span>(
                      {+volume + 1})
                    </div>
                  </>
                ) : null}
              </div> */}
            </div>
            <div className="col-md-5 d-flex align-items-center justify-content-end">
              {song.mastered && songData.songUrl && (
                <button
                  className="master__btn"
                  onClick={() => startDownload(song)}
                >
                  Download
                </button>
              )}
              {!song && !song.mastered && (
                <button
                  className="master__btn"
                  onClick={() => masterSong(song)}
                >
                  Unlock Mastering
                </button>
              )}
            </div>
          </div>
          <div className="wave__container w-96 mx-auto p-2 m-4 shadow-md overflow-none rounded-xl">
            {waveloading && (
              // <div class="spinner">
              //   <div class="rect1"></div>
              //   <div class="rect2"></div>
              //   <div class="rect3"></div>
              //   <div class="rect4"></div>
              //   <div class="rect5"></div>
              // </div>
              <div>
              <RiveComponent className="mx-auto w-32 h-32  shadow-md "
                    
              alt="mixer icon"
            /></div>
            )}
            <div
              id="waveform"
              className="waveform"
              style={{ height: waveloading ? "0px" : "100%" }}
            ></div>
          </div>
          <div className="options d-flex justify-content-between align-items-center">
            {waveloading ? (
              <div>
              <h3 className="text-xl text-purple-300 font-bold text-center mb-4"> Super charging our mastering engine!!</h3>
              <h4 className=" my-2" style={{ color: "#fff" }}>
                Preparing your track ... {masteringDurationLeft}
              </h4>
              </div>
            ) : null}
          </div>
          <div className="container-fluid">
            <h5>Song Title: {song.title}</h5>
            <p style={{ color: "#fff" }}>{currentTime}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

const mapStateToProps = (state) => ({
  currentPlay: state.music.currentPlay,
  shuffle: state.music.shuffle,
  user: state.user.user,
});

const mapDispatchToProps = (dispatch) => ({
  pausePlayCurrentPlay: () => dispatch(pausePlayCurrentPlay()),
  setRepeatAll: (data) => dispatch(setRepeatAll(data)),
  setRepeatOne: (data) => dispatch(setRepeatOne(data)),
  setShuffle: (data) => dispatch(setShuffle(data)),
});

export default connect(mapStateToProps, mapDispatchToProps)(Player);

**Comment by zplata** [comment]
Sorry for the delay - do you mind trying with the latest version? Additionally check out our new guidance on preloading WASM:
https://help.rive.app/runtimes/overview/web-js/preloading-wasm

This will help especially in NextJS applications with loading in the WASM that is necessary to power Rive animations

**Comment by ryparker** [comment]
It would be nice to have a next.js example app and some specific pages in the docs for next.js users since it's got a lot of adoption and many users will run into the same non-trivial issues with rive. Also if you do happen to make an example with next.js could you include content security policy rules? The recommend guidance of using `wasm-unsave-eval` works in firefox but not chrom, brave, or safari.

**Comment by Renesauve** [comment]
Experiencing same issue here, is there a specific loader we need to use for this?

**Comment by nyuudo** [comment]
Same issue here.
Neither importing as Rive or RiveComponent works, or importing as props or as a src, the riv files simply don't render.
I even tried the link "https://cdn.rive.app/animations/vehicles.riv" that appears in the Rive React guide and not even that renders.
Is there a proper REACT JS or NEXT JS loader ?
Maybe there's an objectiely simple and plain way but I cannot seem to find it.

**Comment by meJohnnyRobert** [comment]
> Same issue here.
> Neither importing as Rive or RiveComponent works, or importing as props or as a src, the riv files simply don't render.
> I even tried the link "https://cdn.rive.app/animations/vehicles.riv" that appears in the Rive React guide and not even that renders.
> Is there a proper REACT JS or NEXT JS loader ?
> Maybe there's an objectiely simple and plain way but I cannot seem to find it.

I've managed to get it working in my own project like his:

```typescript
import { useRive } from '@rive-app/react-canvas';

const Logo = () => {

const { RiveComponent } = useRive({

src: "/YourLogo.riv",

autoplay: true,

onLoadError: () => console.log("ERROR LOADING RIVE"),

onLoad: () => console.log("LOADED RIVE"),

})

return (

<div style={{ width: '100px', height: '100px' }}>

<RiveComponent />

</div>

);

};

//then in your page layout in the page.tsx you can place it as per usual:

return (

<div className="flex-1 flex flex-col w-full px-8 sm:max-w-md justify-center gap-2">

<Logo/>```

Just make sure to put the logo file(s) in a public folder. I'm using typescript, tailwind and App Router and I have the logo inside a public folder under the "app" folder.

**Comment by nyuudo** [comment]
Thanks for your suggestion. Finally I was able to render a riv.file. I followed the logic of your code, I just had to add the 'use client' directive to the .tsx file that invoke the riv file.

**Comment by oatlpk** [comment]
@nyuudo i still can't get it, do u mind sharing the repo u were able to render it on please?

**Comment by ivajo26** [comment]
I use CSP policy, but rive needs access unpkg.com

**Comment by ben-katz** [comment]
@meJohnnyRobert thank you! this worked!

Here is what I ended up doing for an interactive button animation:

`/rive.tsx`:

```
"use client";

import { useRive, useStateMachineInput } from '@rive-app/react-canvas';
import { useCallback } from 'react';

export default function RiveEmbed() {
    const { rive, RiveComponent } = useRive({
        src: "/rivedemo.riv",
        stateMachines: "State Machine 1",
        autoplay: true,
        onLoadError: () => console.log("ERROR LOADING RIVE"),
        onLoad: () => console.log("LOADED RIVE"),
    });

    const hoverInput = useStateMachineInput(rive, "State Machine 1", "hover");

    const handleMouseEnter = useCallback(() => {
        hoverInput?.fire();
    }, [hoverInput]);

    const handleMouseLeave = useCallback(() => {
        hoverInput?.fire();
    }, [hoverInput]);

    return (
        <div 
            className='w-[280px] h-[100px] cursor-pointer'
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
        >
            <RiveComponent />
        </div>
    );
}
```
