### ISSUE TITLE
Rive.wasm blocking website load

### ISSUE THREAD

**Issue by carolinmaisenbacher** [rive-app/rive-react#97]
I am currently developing a Gatsby website that uses a few Rive animations with the help of `rive-react`.

In development it works great, however whenever building my website the loading speeds for the first paint get very slow. 

I noticed that a 3rd party request to get `rive.wasm` is what is blocking my website. 
I am attaching some screenshots below.

Do you have any advice how I can make the request faster? Is it possible to host the rive.wasm file e.g. on my own server?

Any help is appreciated!

Here is the request summary, which shows it took 93ms to get the rive file:
<img width="1795" alt="Screenshot 2022-06-15 at 11 40 09" src="https://user-images.githubusercontent.com/32734844/173732689-f262a32f-a0f5-4796-b174-e860914c678c.png">

These are the request details:
<img width="1052" alt="Screenshot 2022-06-15 at 11 41 00" src="https://user-images.githubusercontent.com/32734844/173732695-d1f282b2-ae31-4d52-85cb-c85ceff52739.png">

**Comment by 3lonious** [comment]
im having issues rending on an ec2 for some reason.. it works localy but when i push to developement nothing shows up.. spent the day trying to figure why... since my request looks the same as the screen shot from Carolin. Im wondering if im having the same issue with rending here? cant figure out how to debug at the moment and its sucks cuz i really want to use this anmination and more in my react project

**Comment by zplata** [comment]
Actually, you might be able to host the WASM file on your own server and be able to serve this up!

```
import Rive, { RuntimeLoader } from "@rive-app/react-canvas";

RuntimeLoader.setWasmUrl("http://your-own-server.com/rive.wasm");

function App() {
  return (
    <div>
      <Rive src="https://cdn.rive.app/animations/vehicles.riv" />
    </div>
  );
}
```

We can work on making the URL you'd like to set as a param you pass into `<Rive>` or `useRive()` but you could do this in the meantime, and then it shouldn't try to request the `wasm` from `unpkg` by default.

To download the correlated WASM file for your server, check out the dependency version of `@rive-app/canvas` in the tagged version of `@rive-app/react-canvas` you're consuming. For example, `1.0.71`: https://github.com/rive-app/rive-react/blob/v3.0.15/package.json#L32

The correlated WASM file should be the following URL with the version identified above:
>  https://unpkg.com/@rive-app/canvas@1.0.71/rive.wasm

@carolinmaisenbacher @3lonious

**Comment by 3lonious** [comment]
i feel like maybe there is code missing here? im getting this error?
<img width="1123" alt="Screen Shot 2022-07-05 at 10 12 19 AM" src="https://user-images.githubusercontent.com/46793692/177381099-36940a59-3b17-47eb-8730-0017d67741a6.png">

**Comment by 3lonious** [comment]
hey im unable to install react-canvas with my current config...

any other ideas?

**Comment by 3lonious** [comment]
i may have got it working one sec

**Comment by 3lonious** [comment]
ok its working... like this
<img width="1506" alt="Screen Shot 2022-07-05 at 10 52 15 AM" src="https://user-images.githubusercontent.com/46793692/177387063-63947b6f-6e00-4d2a-b1e1-8df70ac9dbc8.png">

**Comment by 3lonious** [comment]
<img width="748" alt="Screen Shot 2022-07-05 at 10 53 37 AM" src="https://user-images.githubusercontent.com/46793692/177387192-145e7a32-ed45-4703-b847-c20b86febbe0.png">
<img width="841" alt="Screen Shot 2022-07-05 at 10 53 46 AM" src="https://user-images.githubusercontent.com/46793692/177387202-b1bafa9d-3aa0-422e-b6c0-4995d0db9fa2.png">

**Comment by 3lonious** [comment]
needing to get this one tho from cdn? how do i find them to use the way i have setup? 

https://rive.app/community/65-358-iron-giant-demo/

**Comment by 3lonious** [comment]
figured it out with inspect and network calls but would be great to have that url copable from community listings  animation page

**Comment by 3lonious** [comment]
thanks for the help tho on this!

**Comment by carolinmaisenbacher** [comment]
Thank you for your detailed reply @zplata!
Your solution of setting the wasm url with `setWasmUrl` worked flawlessly for me.
